import {
  Settings,
  Building2,
  Clock,
  UserCheck,
  FileText,
  Activity,
  CreditCard,
  Users,
  Briefcase,
} from 'lucide-react'
import { AssumptionSection } from './types'

// AICPA stage descriptions
export const stageDescriptions: Record<string, string> = {
  'Stage 1: Ideation':
    'The Idea - Ideation and Initial Concept: No tangible product exists. Management team typically incomplete. Initial funding from founders, friends, and family. No product revenue and limited expense history. Valuation highly subjective; Backsolve Method most reliable if recent transaction occurred.',
  'Stage 2: Product Development':
    'The Plan - Formalization and Early Development: Product development actively underway, business challenges better understood. Management team being assembled. First or second round of financing (preferred stock) to fund development. No product revenue but substantive expense history. Backsolve Method remains primary valuation tool.',
  'Stage 3: Development Progress':
    'The Product - Nearing Completion: Key development milestones met, product nearing completion with alpha/beta testing. More complete management team in place. Continued financing through preferred stock. Generally no product revenue yet. Valuation approaches expanded to include DCF and market comparables.',
  'Stage 4: Early Revenue':
    'First Sales - Initial Market Entry: Product launched to market with initial customer sales. Complete or near-complete management team. Additional financing rounds for market expansion. Initial product revenues but operating at a loss. Market approach gains prominence alongside DCF methodology.',
  'Stage 5: Revenue Generation':
    'Growth - Market Expansion: Growing sales to expanding customer base with potential market leadership. Management team complete and expanding. Later stage financing through multiple investor groups. Significant revenue growth approaching profitability. Comparable company analysis becomes primary valuation methodology.',
  'Stage 6: Established Operations':
    'Maturity - Profitable Operations: Established market position with sustainable competitive advantages. Experienced and stable management team. Potential for IPO or strategic exit. Profitable operations with positive cash flows. Market multiples and guideline transactions provide reliable valuation benchmarks.',
}

// Define consolidated sections
export const sections: AssumptionSection[] = [
  {
    id: 'methodology',
    name: 'Valuation Methodologies',
    icon: Settings,
    description: 'Select and weight the valuation methodologies',
    fields: [], // Handled by ValuationMethodologySelector
  },
  {
    id: 'company',
    name: 'Company Information',
    icon: Building2,
    description: 'Core company details and incorporation information',
    fields: [
      { id: 'company_name', name: 'Company Name', type: 'text', value: '', required: true },
      { id: 'company_address', name: 'Company Address', type: 'text', value: '' },
      {
        id: 'state_incorporation',
        name: 'State of Incorporation',
        type: 'select',
        value: 'Delaware',
        options: ['Delaware', 'California', 'New York', 'Texas', 'Nevada', 'Wyoming', 'Other'],
        required: true,
      },
      { id: 'incorporation_date', name: 'Date of Incorporation', type: 'date', value: '' },
      {
        id: 'industry',
        name: 'Industry',
        type: 'select',
        value: '',
        options: [
          'Technology',
          'Healthcare',
          'Financial Services',
          'Consumer',
          'Industrial',
          'Energy',
          'Real Estate',
          'Other',
        ],
        required: true,
      },
      { id: 'fiscal_year_end', name: 'Fiscal Year End', type: 'date', value: '', required: true },
      {
        id: 'currency',
        name: 'Currency',
        type: 'select',
        value: 'USD',
        options: ['USD', 'EUR', 'GBP', 'CAD'],
      },
      {
        id: 'discounting_convention',
        name: 'Discounting Convention',
        type: 'select',
        value: 'Mid-Year',
        options: ['Mid-Year', 'End-Year'],
        description: 'When cash flows are assumed to occur during the period',
      },
    ],
  },
  {
    id: 'company_profile',
    name: 'Company Profile',
    icon: Briefcase,
    description: 'Detailed company profile and stakeholder information',
    fields: [
      {
        id: 'company_stage',
        name: 'Company Stage',
        type: 'select',
        value: '',
        options: [
          'Stage 1: Ideation',
          'Stage 2: Product Development',
          'Stage 3: Development Progress',
          'Stage 4: Early Revenue',
          'Stage 5: Revenue Generation',
          'Stage 6: Established Operations',
        ],
        required: true,
      },
      {
        id: 'stage_description',
        name: 'Stage Description',
        type: 'textarea',
        value: '',
        placeholder: 'Select a stage to auto-populate or enter custom description',
        description: 'AICPA stage description - automatically populated when stage is selected',
      },
      {
        id: 'company_description',
        name: 'Company Description',
        type: 'textarea',
        value: '',
        placeholder: 'Brief description of the company and its mission',
      },
      {
        id: 'products_services',
        name: 'Products & Services',
        type: 'textarea',
        value: '',
        placeholder: 'Description of main products and services offered',
      },
      {
        id: 'management_team',
        name: 'Management Team',
        type: 'team',
        value: [],
        description: 'Key management team members',
      },
      {
        id: 'key_investors',
        name: 'Key Investors',
        type: 'investors',
        value: [],
        description: 'Major investors and stakeholders',
      },
      {
        id: 'industry_description',
        name: 'Industry Description',
        type: 'textarea',
        value: '',
        placeholder: 'Description of the industry and market dynamics',
      },
    ],
  },
  {
    id: 'valuation_details',
    name: 'Valuation Details',
    icon: FileText,
    description: 'Purpose and standards for the valuation',
    fields: [
      { id: 'valuation_date', name: 'Valuation Date', type: 'date', value: '', required: true },
      { id: 'report_date', name: 'Report Date', type: 'date', value: '' },
      {
        id: 'subject_security',
        name: 'Subject Security',
        type: 'text',
        value: '',
        placeholder: 'e.g., Common Stock, Series A Preferred Stock',
        description: 'The type of security being valued',
        required: true,
      },
      {
        id: 'valuation_purpose',
        name: 'Valuation Purpose',
        type: 'text',
        value: 'Section 409A of the Internal Revenue Code',
        required: true,
      },
      {
        id: 'standard_of_value',
        name: 'Standard of Value',
        type: 'select',
        value: 'Fair Market Value',
        options: ['Fair Market Value', 'Fair Value', 'Investment Value', 'Intrinsic Value'],
        required: true,
      },
      {
        id: 'premise_of_value',
        name: 'Premise of Value',
        type: 'select',
        value: 'Going Concern',
        options: ['Going Concern', 'Liquidation', 'Orderly Liquidation', 'Forced Liquidation'],
        required: true,
      },
    ],
  },
  {
    id: 'designee',
    name: 'Designee Information',
    icon: Users,
    description: 'Person the valuation report will be addressed to',
    fields: [
      {
        id: 'designee_prefix',
        name: 'Prefix',
        type: 'select',
        value: 'Mr.',
        options: ['Mr.', 'Ms.', 'Mrs.', 'Dr.', 'Prof.'],
        required: true,
      },
      { id: 'designee_first_name', name: 'First Name', type: 'text', value: '', required: true },
      { id: 'designee_last_name', name: 'Last Name', type: 'text', value: '', required: true },
      {
        id: 'designee_title',
        name: 'Title',
        type: 'text',
        value: '',
        placeholder: 'e.g., CEO, CFO, Board Member',
        required: true,
      },
      {
        id: 'engagement_letter_date',
        name: 'Engagement Letter Date',
        type: 'date',
        value: '',
        description: 'Date the engagement letter was signed',
        required: true,
      },
    ],
  },
  {
    id: 'appraiser',
    name: 'Appraiser Information',
    icon: UserCheck,
    description: 'Details about the valuation professional',
    fields: [
      { id: 'appraiser_name', name: 'Appraiser Name', type: 'text', value: '', required: true },
      { id: 'appraiser_firm', name: 'Appraiser Firm', type: 'text', value: '', required: true },
      {
        id: 'appraiser_credentials',
        name: 'Credentials (ASA, CFA, etc.)',
        type: 'text',
        value: '',
      },
      { id: 'appraiser_phone', name: 'Contact Phone', type: 'text', value: '' },
      { id: 'appraiser_email', name: 'Contact Email', type: 'text', value: '', required: true },
    ],
  },
  {
    id: 'analysis_periods',
    name: 'Analysis Periods',
    icon: Clock,
    description: 'Historical and projection periods for analysis',
    fields: [
      {
        id: 'historical_years',
        name: 'Number of Historical Years',
        type: 'number',
        value: 3,
        description: 'Number of historical fiscal years to include (1-10)',
        required: true,
      },
      {
        id: 'projection_years',
        name: 'Projection Years',
        type: 'number',
        value: 5,
        description: 'Number of years to project (1-30)',
        required: true,
      },
    ],
  },
  {
    id: 'volatility',
    name: 'Volatility & Risk-Free Rate',
    icon: Activity,
    description: 'Market volatility and risk-free rate parameters',
    fields: [
      {
        id: 'risk_free_rate',
        name: 'Risk-Free Rate (%)',
        type: 'percentage',
        value: 4.5,
        description: 'Current risk-free rate for option pricing',
        required: true,
      },
      {
        id: 'equity_volatility',
        name: 'Equity Volatility (%)',
        type: 'percentage',
        value: 60,
        description: 'Expected volatility of equity',
      },
      {
        id: 'time_to_liquidity',
        name: 'Expected Time to Liquidity (Years)',
        type: 'number',
        value: 3,
        description: 'Expected time until a liquidity event',
      },
    ],
  },
  {
    id: 'recent_transactions',
    name: 'Recent Transactions',
    icon: CreditCard,
    description: 'Recent financing or transaction information',
    fields: [
      { id: 'last_financing_date', name: 'Last Financing Date', type: 'date', value: '' },
      { id: 'last_financing_amount', name: 'Last Financing Amount', type: 'currency', value: '' },
      {
        id: 'last_financing_valuation',
        name: 'Post-Money Valuation',
        type: 'currency',
        value: '',
      },
      {
        id: 'last_financing_type',
        name: 'Financing Type',
        type: 'select',
        value: '',
        options: [
          'Series Seed',
          'Series A',
          'Series B',
          'Series C',
          'Series D+',
          'Convertible Note',
          'SAFE',
          'Other',
        ],
      },
    ],
  },
]